version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./empresa.db:/usr/src/app/empresa.db
      - ./src:/usr/src/app/src
    environment:
      - NODE_ENV=production
    restart: unless-stopped